name: "Scan IaC"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  analyze:
    name: Analyze
    runs-on: 'ubuntu-latest'
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master 
        with:
          api-key: ${{ secrets.BC_API_KEY }}
          output_format: cli,sarif
          output_file_path: console,results.sarif
        
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: results.sarif

      # - name: Get Token
      #   id: get_workflow_token
      #   uses: peter-murray/workflow-application-token-action@v2
      #   with:
      #     organization: advanced-security
      #     application_id: ${{ secrets.OCTODEMOBOT_APPLICATION_ID_REPO_AUTOMATION }}
      #     application_private_key: ${{ secrets.OCTODEMOBOT_APPLICATION_KEY_REPO_AUTOMATION }}
  
      # - name: Checkout advanced-security/codeql-extractor-iac action
      #   uses: actions/checkout@v4
      #   with:
      #     repository: advanced-security/codeql-extractor-iac
      #     path: codeql-extractor-iac
      #     token: ${{ secrets.GH_TOKEN }}
  
      # - name: Automatically try and enable GitHub Advanced Security 
      #   uses: ./codeql-extractor-iac
      #   with:
      #     source-root: "main"
      #     token: ${{ secrets.GH_TOKEN }}
